# Generated by Django 4.2.16 on 2025-02-21 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="intro",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="posted_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
