# Generated by Django 4.2.16 on 2025-03-14 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_post_user_likes_likes_post_user_unique"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Likes",
            new_name="Like",
        ),
    ]
