# Generated by Django 4.2.16 on 2025-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_likes_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
